### PR TITLE
Code and command args improvements

### PR DESCRIPTION
**Pull request by dvinciguerra**
### What was a problem?

Project has a problem caused by using Switch module and the complexity of CLI arguments made us need a better strategy to parse them.

### How this PR fixes the problem?

* Removing Switch dependency
* Rewrite commands structure to be more easy and scalable
* Implement the use of Getopt::Long to parse individual subcommand options
* Improve code style guide by using community patterns
* Use of pertidy for code formatting using a modern rules
* Merging with WIP `develop` branch
* Improve gitignore file
* Add `cpanfile` to improve development experience and give a new way to use and install dependencies. 

### Check lists (check `x` in `[ ]` of list items)

- [ ] Test passed (soon)
- [x] Coding style (indentation, etc)

### Additional Comments (if any)

{Please write here}

### CODE REVIEW

**Comment by GouveaHeitor** [comment]
Hi @dvinciguerra,

I run a simple test and got the following error:

Screenshot from 2020-02-28 10-06-56



Thx for this PR!

**Comment by dvinciguerra** [comment]
cc @GouveaHeitor 

I submit a fix for the issue... sorry about that!

**Comment by GouveaHeitor** [comment]
Hi @dvinciguerra,

I had many problems in diving / testing the PR's performed by the community and what I already had in developing ...

So I ended up reading the contributions and I'm doing micro-updates on the master ...

If you can check, I am grateful!

**Comment by GouveaHeitor** [comment]
@all-contributors please add @dvinciguerra for code

**Pull request closed without merging**
