### PR TITLE
checking for exists /etc/tor/torrc & rename if exist

### PR DESCRIPTION
**Pull request by driedbrains**
### What was a problem?

overwrites torrc file when copying from .config

### How this PR fixes the problem?

checking for exists /etc/tor/torrc & rename if exist to torrc.bak

### CODE REVIEW

**Comment by bmeneguele** [comment]
Hi @driedbrains! Just fyi.. this situation was already handled by PR #80 which was merged in "develop" branch but didn't make "master" yet. However, using a backup file could be helpful.. maybe when the user issues the install command with "-f"?... not sure.

**Comment by driedbrains** [comment]
Hi @bmeneguele maybe, but users can be forgetful.

**Comment by bmeneguele** [comment]
> Hi @bmeneguele maybe, but users can be forgetful... like me for example :)

yep, but that's why the code brought with #80 doesn't take any action in case the user don't use the "-f" option. It'll only warn about the existence of the config file under nipe's project directory.

**Comment by driedbrains** [comment]
Ok, "-f" good idea, but I would add, however, the ability to save the file, and not just rewrite

**Comment by bmeneguele** [comment]
> Ok, "-f" good idea, but I would add, however, the ability to save the file, and not just rewrite

Ah yes.. I'm fine with that. Plus a message about the "old config" being backed up.
I think that's a good addition!

+1

**Comment by GouveaHeitor** [comment]
Hi @driedbrains,

First of all thank you very much for your contribution, it is very valid!!

We believe that we can proceed as follows:

- We keep the "-f" option created by @bmeneguele
- But we will take the action of making a "backup" of the original file, automatically, as suggested by @driedbrains 

@driedbrains Whenever you do a PR, do it for the "develop" branch, it has the latest updates from Nipe. Can you write the code for these features we discussed here? If you need help just let me know.

Thx!!!

**Comment by mcasdfgf** [comment]
@GouveaHeitor, ok. I can

**Comment by GouveaHeitor** [comment]
@driedbrains Could you review your PRs? They are adding/removing things that are not entirely directed at their suggestions ... I would like to see a PR somewhat cleaner please

**Comment by GouveaHeitor** [comment]
Hi @driedbrains, you can resolve the conflicts here?

**Comment by GouveaHeitor** [comment]
Hi @driedbrains,

Recently I was reading the tor manual and I discovered an option called "-f", where I configure the torrc file that I want, allowing me to keep the user's torrc file untouchable... I believe this is the best option for Nipe, in order to avoid any conflict or unhealthy movement.

This will soon be implemented in Nipe

Thx

**Comment by GouveaHeitor** [comment]
See #104.

**Pull request closed without merging**
